name: AI4Code
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - hydra-core=1.0.6
  - mlflow==1.14.1
  - pip=20.3.3
  - pip:
    -wandb==0.10.31
    - zipp
    - boto3==1.21.12
    - kaggle== 1..5.12
